export const actions = {
    profile: {
        PROFILE_DATA_FETCHED: "PROFILE_DATA_FETCHED",
        PROFILE_DATA_FETCHING: "PROFILE_DATA_FETCHING",
        DATA_FETCH_ERROR: "DATA_FETCH_ERROR",
        USER_DATA_FETCH: "USER_DATA_FETCH",
        USER_DATA_EDIT: "USER_DATA_EDIT",
        IMAGE_UPDATED: "IMAGE_UPDATED",
    },

    post: {
        POST_DATA_FETCHED: "POST_DATA_FETCHED",
        POST_DATA_FETCHING: "POST_DATA_FETCHING",
        DATA_FETCH_ERROR: "DATA_FETCH_ERROR",
        POST_EDITED: "POST_EDITED",
        POST_DELETED: "POST_DELETED",
        POST_CREATED: "POST_CREATED"
    },

}